services:
  postgres:
    image: postgres:16-alpine
    container_name: db-watchdog-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgres/setup.sh:/docker-entrypoint-initdb.d/setup.sh"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_watchdog -h localhost -p 5432 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: db-watchdog-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
    ports:
      - "8180:8180"
    command: start-dev --http-port=8180 --import-realm
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
