name: Scala CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  formatting-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Scala + sbt
        uses: coursier/setup-action@v2
        with:
          java-version: 21
          scala-version: 3.8.1
          coursier-version: 2.1.2

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt', '**/project/*.scala') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Scalafmt check
        run: |
          cd server
          sbt scalafmtCheckAll

      - name: Scalafix check
        run: |
          cd server
          sbt "scalafix --check"